"use client";

import React from "react";
import ProjectsCarousel from "@/components/projects/Projects";

export default function GamingPage() {

  const projects = [
    {
      id: 1,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/2.jpg",
      isCenter: false,
    },
    {
      id: 3,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/4.jpg",
      isCenter: false,
    },
    {
      id: 5,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/5.jpg",
      isCenter: false,
    },
        {
      id: 4,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/3.jpg",
      isCenter: false,
    },
    {
      id: 7,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/7.jpg",
      isCenter: false,
    },
        {
      id: 6,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/6.jpg",
      isCenter: false,
    },
    {
      id: 8,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/8.jpg",
      isCenter: false,
    },
    {
      id: 9,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/9.jpg",
      isCenter: false,
    },
    {
      id: 10,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/10.jpg",
      isCenter: false,
    },
    {
      id: 11,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/11.jpg",
      isCenter: false,
    },
    {
      id: 12,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/12.jpg",
      isCenter: false,
    },
    {
      id: 13,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/13.jpg",
      isCenter: false,
    },
    {
      id: 16,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/16.jpg",
      isCenter: false,
    },
    {
      id: 15,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/15.jpg",
      isCenter: false,
    },
        {
      id: 14,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/14.jpg",
      isCenter: false,
    },
    {
      id: 17,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/17.jpg",
      isCenter: false,
    },
    {
      id: 19,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/19.jpg",
      isCenter: false,
    },
    {
      id: 18,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Characters",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/2d/18.jpg",
      isCenter: false,
    },
    {
      id: 20,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/banners/1.jpg",
      isCenter: false,
    },
    {
      id: 21,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/banners/2.jpg",
      isCenter: false,
    },
    {
      id: 22,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/banners/3.jpg",
      isCenter: false,
    },
    {
      id: 24,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/banners/4.jpg",
      isCenter: false,
    },
    {
      id: 25,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/banners/5.jpg",
      isCenter: false,
    },
    {
      id: 26,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/chibbi/1.jpg",
      isCenter: false,
    },
    {
      id: 27,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/chibbi/2.jpg",
      isCenter: false,
    },
    {
      id: 28,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/chibbi/3.jpg",
      isCenter: false,
    },
    {
      id: 29,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/chibbi/4.jpg",
      isCenter: false,
    },
    {
      id: 30,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/1.jpg",
      isCenter: false,
    },
    {
      id: 31,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/2.jpg",
      isCenter: false,
    },
    {
      id: 32,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/3.jpg",
      isCenter: false,
    },
    {
      id: 33,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/4.jpg",
      isCenter: false,
    },
    {
      id: 34,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/5.jpg",
      isCenter: false,
    },
    {
      id: 35,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/6.jpg",
      isCenter: false,
    },
    {
      id: 36,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/7.jpg",
      isCenter: false,
    },
    {
      id: 37,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/8.jpg",
      isCenter: false,
    },
    {
      id: 38,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/9.jpg",
      isCenter: false,
    },
    {
      id: 39,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/10.jpg",
      isCenter: false,
    },
    {
      id: 40,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/11.jpg",
      isCenter: false,
    },
    {
      id: 41,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/12.jpg",
      isCenter: false,
    },
    {
      id: 42,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/13.jpg",
      isCenter: false,
    },
    {
      id: 43,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Emotes",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/emotes/14.jpg",
      isCenter: false,
    },
    {
      id: 45,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/1.jpg",
      isCenter: false,
    },
    {
      id: 46,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/2.jpg",
      isCenter: false,
    },
    {
      id: 47,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/3.jpg",
      isCenter: false,
    },
    {
      id: 48,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/4.jpg",
      isCenter: false,
    },
    {
      id: 49,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/5.jpg",
      isCenter: false,
    },
    {
      id: 50,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/6.jpg",
      isCenter: false,
    },
    {
      id: 51,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/7.jpg",
      isCenter: false,
    },
    {
      id: 52,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/8.jpg",
      isCenter: false,
    },
    {
      id: 53,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/9.jpg",
      isCenter: false,
    },
    {
      id: 54,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Overlays",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/overlays/10.jpg",
      isCenter: false,
    },
    {
      id: 55,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Schedules",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/schedules/1.jpg",
      isCenter: false,
    },
    {
      id: 56,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Schedules",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/schedules/2.jpg",
      isCenter: false,
    },
    {
      id: 57,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Sub Badges",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/sub/1.jpg",
      isCenter: false,
    },
    {
      id: 58,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Sub Badges",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/sub/2.jpg",
      isCenter: false,
    },
    {
      id: 59,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Sub Badges",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/sub/3.jpg",
      isCenter: false,
    },
    {
      id: 60,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Sub Badges",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/sub/4.jpg",
      isCenter: false,
    },
    {
      id: 61,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Vtuber",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/vtubers/1.jpg",
      isCenter: false,
    },
    {
      id: 62,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Vtuber",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/vtubers/2.jpg",
      isCenter: false,
    },
    {
      id: 63,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Vtuber",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/vtubers/3.jpg",
      isCenter: false,
    },
    {
      id: 64,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Gaming",
      subcategory: "Vtuber",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/gaming/vtubers/4.jpg",
      isCenter: false,
    },
  ];

  const webSubcategories = ["Logo", "Banners", "Emotes", "Overlays", "Characters", "Schedules", "Vtuber", "Sub Badges"];

  const handleProjectClick = (project) => {
    console.log("Project clicked:", project);
  };

  return (
          <ProjectsCarousel
            projects={projects}
            subcategories={webSubcategories}
            category="Gaming"
            visiblePerPage={3}
            onProjectClick={handleProjectClick}
            showDetails={false}
          />

  );
}
