"use client";

import React from "react";
import ProjectsCarousel from "@/components/projects/Projects";

export default function WebDevelopmentPage() {
  // ---- TODO: fill this array with your project objects ----
  // Example project object shape:
  // {
  //   id: 1,
  //   title: "Project Name",
  //   subtitle: "Short tag",
  //   category: "Web Development",
  //   subcategory: "WordPress", // or "Shopify" or "Custom"
  //   description: "Short description",
  //   bgGradient: "from-teal-900 via-black to-teal-900",
  //   textColor: "text-emerald-400",
  //   accentColor: "emerald-400",
  //   icon: null, // or an imported icon component
  //   svgPattern: "circuit",
  //   image: "/path/to/image.jpg",
  //   isCenter: false
  // }
  const projects = [
  {
    id: 1,
    title: "Metro Realty",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/1.jpg",
    isCenter: false,
  },
  {
    id: 2,
    title: "NGO Loob",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/2.jpg",
    isCenter: false,
  },
  {
    id: 3,
    title: "PMC",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/3.jpg",
    isCenter: false,
  },
  {
    id: 4,
    title: "Rockford Mortage",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/4.jpg",
    isCenter: false,
  },
  {
    id: 5,
    title: "Speaki",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/5.jpg",
    isCenter: false,
  },
  {
    id: 6,
    title: "Taha Khan",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/6.jpg",
    isCenter: false,
  },
  {
    id: 7,
    title: "TSB",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/7.jpg",
    isCenter: false,
  },
  {
    id: 8,
    title: "Verve",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/8.jpg",
    isCenter: false,
  },
  {
    id: 9,
    title: "ZVCO",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/9.jpg",
    isCenter: false,
  },
  {
    id: 10,
    title: "14 Star Limo",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/10.jpg",
    isCenter: false,
  },
  {
    id: 11,
    title: "Ali Jafri",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/11.jpg",
    isCenter: false,
  },
  {
    id: 12,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/12.jpg",
    isCenter: false,
  },
  {
    id: 13,
    title: "The Antenna",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/13.jpg",
    isCenter: false,
  },
  {
    id: 14,
    title: "Aussie Crops",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/14.jpg",
    isCenter: false,
  },
  {
    id: 15,
    title: "Baseus",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/15.jpg",
    isCenter: false,
  },
  {
    id: 16,
    title: "Career Connector",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/16.jpg",
    isCenter: false,
  },
  {
    id: 17,
    title: "Daraz Oye",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/17.jpg",
    isCenter: false,
  },
  {
    id: 18,
    title: "Ed Lab",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/18.jpg",
    isCenter: false,
  },
  {
    id: 19,
    title: "Fintalk",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/19.jpg",
    isCenter: false,
  },
  {
    id: 20,
    title: "GCI",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/20.jpg",
    isCenter: false,
  },
  {
    id: 21,
    title: "Herbion",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/21.jpg",
    isCenter: false,
  },
  {
    id: 22,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/22.jpg",
    isCenter: false,
  },
  {
    id: 23,
    title: "Maria Jewllers",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "WordPress",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/wordpress/23.jpg",
    isCenter: false,
  },
  {
    id: 24,
    title: "Bechlo",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Shopify",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/shopify/1.jpg",
    isCenter: false,
  },
  {
    id: 25,
    title: "Disposable",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Shopify",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/shopify/2.jpg",
    isCenter: false,
  },
  {
    id: 26,
    title: "Jayshrees Rivaz",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Shopify",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/shopify/3.jpg",
    isCenter: false,
  },
  {
    id: 27,
    title: "Pop Charm",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Shopify",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/shopify/4.jpg",
    isCenter: false,
  },
  {
    id: 28,
    title: "Rentoza",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Shopify",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/shopify/5.jpg",
    isCenter: false,
  },
  {
    id: 29,
    title: "Varadona",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Shopify",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/shopify/6.jpg",
    isCenter: false,
  },
  {
    id: 30,
    title: "Baseus",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/1.jpg",
    isCenter: false,
  },
  {
    id: 31,
    title: "IRC Booking System",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/2.jpg",
    isCenter: false,
  },
  {
    id: 33,
    title: "Cars Finder Admin",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/3.jpg",
    isCenter: false,
  },
  {
    id: 34,
    title: "Cars Finder Pro",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/4.jpg",
    isCenter: false,
  },
  {
    id: 35,
    title: "Auto Cars",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/5.jpg",
    isCenter: false,
  },
  {
    id: 36,
    title: "Cyber Security",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/6.jpg",
    isCenter: false,
  },
  {
    id: 37,
    title: "Clean UI",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/7.jpg",
    isCenter: false,
  },
  {
    id: 38,
    title: "O360",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/8.jpg",
    isCenter: false,
  },
  {
    id: 39,
    title: "Smart Tender",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/9.jpg",
    isCenter: false,
  },
  {
    id: 40,
    title: "USAMPAC",
    subtitle: "Short tag",
    category: "UI/UX",
    subcategory: "Custom",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/uiux/custom/10.jpg",
    isCenter: false,
  },
];


  const webSubcategories = ["WordPress", "Shopify", "Custom"];

  const handleProjectClick = (project) => {
    // replace with navigation to project detail or modal open
    console.log("Project clicked:", project);
  };

  return (
          <ProjectsCarousel
            projects={projects}
            subcategories={webSubcategories}
            category="UI/UX"
            visiblePerPage={3}
            onProjectClick={handleProjectClick}
          />

  );
}
