"use client";

import React from "react";
import ProjectsCarousel from "@/components/projects/Projects";

export default function GamingPage() {

  const projects = [
    {
      id: 1,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/1.jpg",
      isCenter: false,
    },
    {
      id: 2,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/2.jpg",
      isCenter: false,
    },
    {
      id: 3,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/3.jpg",
      isCenter: false,
    },
    {
      id: 4,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/4.jpg",
      isCenter: false,
    },
    {
      id: 5,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/5.jpg",
      isCenter: false,
    },
    {
      id: 6,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/6.jpg",
      isCenter: false,
    },
    {
      id: 9,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Book Covers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/books/1.jpg",
      isCenter: false,
    },
    {
      id: 10,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Book Covers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/books/2.jpg",
      isCenter: false,
    },
    {
      id: 11,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Book Covers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/books/3.jpg",
      isCenter: false,
    },
    {
      id: 12,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/1.jpg",
      isCenter: false,
    },
    {
      id: 13,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/2.jpg",
      isCenter: false,
    },
    {
      id: 14,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/3.jpg",
      isCenter: false,
    },
    {
      id: 15,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/4.jpg",
      isCenter: false,
    },
    {
      id: 16,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/5.jpg",
      isCenter: false,
    },
    {
      id: 17,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/6.jpg",
      isCenter: false,
    },
    {
      id: 18,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/7.jpg",
      isCenter: false,
    },
    {
      id: 19,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/8.jpg",
      isCenter: false,
    },
    {
      id: 20,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/9.jpg",
      isCenter: false,
    },
    {
      id: 21,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/10.jpg",
      isCenter: false,
    },
    {
      id: 22,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/11.jpg",
      isCenter: false,
    },
      {
    id: 23,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/12.jpg",
    isCenter: false,
  },
  {
    id: 24,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/13.jpg",
    isCenter: false,
  },
  {
    id: 25,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/14.jpg",
    isCenter: false,
  },
  {
    id: 26,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/15.jpg",
    isCenter: false,
  },
  {
    id: 27,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/16.jpg",
    isCenter: false,
  },
  {
    id: 28,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/17.jpg",
    isCenter: false,
  },
  {
    id: 29,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/18.jpg",
    isCenter: false,
  },
  {
    id: 30,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/19.jpg",
    isCenter: false,
  },
  {
    id: 31,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/20.jpg",
    isCenter: false,
  },
  {
    id: 32,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/21.jpg",
    isCenter: false,
  },
  {
    id: 33,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/22.jpg",
    isCenter: false,
  },
  {
    id: 34,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/23.jpg",
    isCenter: false,
  },
  {
    id: 35,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/24.jpg",
    isCenter: false,
  },
  {
    id: 36,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/25.jpg",
    isCenter: false,
  },
  {
    id: 37,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/26.jpg",
    isCenter: false,
  },
  {
    id: 38,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/27.jpg",
    isCenter: false,
  },
  {
    id: 39,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/28.jpg",
    isCenter: false,
  },
  {
    id: 40,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Logo",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/logos/29.jpg",
    isCenter: false,
  },
  {
    id: 41,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/1.jpg",
    isCenter: false,
  },
  {
    id: 42,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/2.jpg",
    isCenter: false,
  },
  {
    id: 43,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/3.jpg",
    isCenter: false,
  },
  {
    id: 44,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/4.jpg",
    isCenter: false,
  },
  {
    id: 45,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/5.jpg",
    isCenter: false,
  },
  {
    id: 46,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/6.jpg",
    isCenter: false,
  },
  {
    id: 47,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/7.jpg",
    isCenter: false,
  },
  {
    id: 48,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/8.jpg",
    isCenter: false,
  },
  {
    id: 49,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/9.jpg",
    isCenter: false,
  },
  {
    id: 50,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/10.jpg",
    isCenter: false,
  },
  {
    id: 51,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/11.jpg",
    isCenter: false,
  },
  {
    id: 51,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/12.jpg",
    isCenter: false,
  },
  {
    id: 52,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/13.jpg",
    isCenter: false,
  },
  {
    id: 53,
    title: "Antenna Now",
    subtitle: "Short tag",
    category: "Corporate",
    subcategory: "Thumbnails",
    description: "Short description",
    bgGradient: "from-teal-900 via-black to-teal-900",
    textColor: "text-emerald-400",
    accentColor: "emerald-400",
    icon: null,
    svgPattern: "circuit",
    image: "/assets/projects/corporate/thumbs/14.jpg",
    isCenter: false,
  },

  ];

  const webSubcategories = ["Logo", "Banners", "Book Covers", "Thumbnails"];

  const handleProjectClick = (project) => {
    console.log("Project clicked:", project);
  };

  return (
          <ProjectsCarousel
            projects={projects}
            subcategories={webSubcategories}
            category="Corporate"
            visiblePerPage={3}
            onProjectClick={handleProjectClick}
            showDetails={false}
          />

  );
}
