import React from "react";
import ProjectsCarousel from "@/components/projects/Projects";
import { Suspense } from "react";

function mulberry32(seed) {
  return function () {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleWithSeed(array, seed = 1) {
  const random = mulberry32(seed);
  return array
    .map((item) => ({ item, sort: random() }))
    .sort((a, b) => a.sort - b.sort)
    .map(({ item }, index) => ({ ...item, id: index + 1 }));
}

function interleaveBySubcategory(projects, order) {
  const groups = projects.reduce((acc, project) => {
    if (!acc[project.subcategory]) acc[project.subcategory] = [];
    acc[project.subcategory].push(project);
    return acc;
  }, {});
  const result = [];
  let added = true;

  while (added) {
    added = false;
    for (const sub of order) {
      if (groups[sub] && groups[sub].length > 0) {
        result.push(groups[sub].shift());
        added = true;
      }
    }
  }

  return result;
}

export default function GamingPage() {
  let projects = [
    {
      id: 1,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/1.jpg",
      isCenter: false,
    },
    {
      id: 2,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/2.jpg",
      isCenter: false,
    },
    {
      id: 3,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/3.jpg",
      isCenter: false,
    },
    {
      id: 4,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/4.jpg",
      isCenter: false,
    },
    {
      id: 5,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/5.jpg",
      isCenter: false,
    },
    {
      id: 6,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/6.jpg",
      isCenter: false,
    },
    {
      id: 7,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/7.jpg",
      isCenter: false,
    },
    {
      id: 8,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/8.jpg",
      isCenter: false,
    },
    {
      id: 9,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/9.jpg",
      isCenter: false,
    },
    {
      id: 10,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/10.jpg",
      isCenter: false,
    },
    {
      id: 11,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/11.jpg",
      isCenter: false,
    },
    {
      id: 12,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Banners",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/banners/12.jpg",
      isCenter: false,
    },
    {
      id: 13,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Book Covers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/books/1.jpg",
      isCenter: false,
    },
    {
      id: 14,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Book Covers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/books/2.jpg",
      isCenter: false,
    },
    {
      id: 15,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Book Covers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/books/3.jpg",
      isCenter: false,
    },
    {
      id: 16,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/1.jpg",
      isCenter: false,
    },
    {
      id: 17,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/2.jpg",
      isCenter: false,
    },
    {
      id: 18,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/3.jpg",
      isCenter: false,
    },
    {
      id: 19,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/4.jpg",
      isCenter: false,
    },
    {
      id: 20,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/5.jpg",
      isCenter: false,
    },
    {
      id: 21,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/6.jpg",
      isCenter: false,
    },
    {
      id: 22,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/7.jpg",
      isCenter: false,
    },
    {
      id: 23,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/8.jpg",
      isCenter: false,
    },
    {
      id: 24,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/9.jpg",
      isCenter: false,
    },
    {
      id: 25,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/10.jpg",
      isCenter: false,
    },
    {
      id: 26,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/11.jpg",
      isCenter: false,
    },
    {
      id: 27,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/12.jpg",
      isCenter: false,
    },
    {
      id: 28,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/13.jpg",
      isCenter: false,
    },
    {
      id: 29,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/14.jpg",
      isCenter: false,
    },
    {
      id: 30,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/15.jpg",
      isCenter: false,
    },
    {
      id: 31,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/16.jpg",
      isCenter: false,
    },
    {
      id: 32,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/17.jpg",
      isCenter: false,
    },
    {
      id: 33,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/18.jpg",
      isCenter: false,
    },
    {
      id: 34,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/19.jpg",
      isCenter: false,
    },
    {
      id: 35,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/20.jpg",
      isCenter: false,
    },
    {
      id: 36,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/21.jpg",
      isCenter: false,
    },
    {
      id: 37,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/22.jpg",
      isCenter: false,
    },
    {
      id: 38,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/23.jpg",
      isCenter: false,
    },
    {
      id: 39,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/24.jpg",
      isCenter: false,
    },
    {
      id: 40,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Logo",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/logos/25.jpg",
      isCenter: false,
    },
    {
      id: 41,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/4.jpg",
      isCenter: false,
    },
    {
      id: 42,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/5.jpg",
      isCenter: false,
    },
    {
      id: 43,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/6.jpg",
      isCenter: false,
    },
    {
      id: 44,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/7.jpg",
      isCenter: false,
    },
    {
      id: 45,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/8.jpg",
      isCenter: false,
    },
    {
      id: 46,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/9.jpg",
      isCenter: false,
    },
    {
      id: 47,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/10.jpg",
      isCenter: false,
    },
    {
      id: 48,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/11.jpg",
      isCenter: false,
    },
    {
      id: 49,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/12.jpg",
      isCenter: false,
    },
    {
      id: 50,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/13.jpg",
      isCenter: false,
    },
    {
      id: 51,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Thumbnails",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/thumbs/14.jpg",
      isCenter: false,
    },
    {
      id: 52,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Business Cards",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/business/1.jpg",
      isCenter: false,
    },
    {
      id: 53,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Business Cards",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/business/3.jpg",
      isCenter: false,
    },
    {
      id: 54,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Business Cards",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/business/4.jpg",
      isCenter: false,
    },
    {
      id: 55,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Business Cards",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/business/5.jpg",
      isCenter: false,
    },
    {
      id: 56,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Business Cards",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/business/6.jpg",
      isCenter: false,
    },
    {
      id: 57,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Business Cards",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/business/7.jpg",
      isCenter: false,
    },
    {
      id: 58,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Flyers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/flyers/1.jpg",
      isCenter: false,
    },
    {
      id: 59,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Flyers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/flyers/2.jpg",
      isCenter: false,
    },
    {
      id: 60,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Flyers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/flyers/3.jpg",
      isCenter: false,
    },
    {
      id: 61,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Flyers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/flyers/4.jpg",
      isCenter: false,
    },
    {
      id: 62,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Flyers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/flyers/5.jpg",
      isCenter: false,
    },
    {
      id: 63,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Flyers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/flyers/6.jpg",
      isCenter: false,
    },
    {
      id: 64,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Flyers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/flyers/7.jpg",
      isCenter: false,
    },
    {
      id: 65,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Flyers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/flyers/8.jpg",
      isCenter: false,
    },
    {
      id: 66,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/1.jpg",
      isCenter: false,
    },
    {
      id: 67,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/2.jpg",
      isCenter: false,
    },
    {
      id: 68,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/3.jpg",
      isCenter: false,
    },
    {
      id: 69,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/4.jpg",
      isCenter: false,
    },
    {
      id: 70,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/5.jpg",
      isCenter: false,
    },
    {
      id: 71,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/6.jpg",
      isCenter: false,
    },
    {
      id: 72,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/7.jpg",
      isCenter: false,
    },
    {
      id: 73,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/8.jpg",
      isCenter: false,
    },
    {
      id: 74,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/9.jpg",
      isCenter: false,
    },
    {
      id: 75,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/10.jpg",
      isCenter: false,
    },
    {
      id: 76,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/11.jpg",
      isCenter: false,
    },
    {
      id: 77,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/12.jpg",
      isCenter: false,
    },
    {
      id: 78,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/13.jpg",
      isCenter: false,
    },
    {
      id: 79,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/14.jpg",
      isCenter: false,
    },
    {
      id: 80,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/15.jpg",
      isCenter: false,
    },
    {
      id: 81,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/16.jpg",
      isCenter: false,
    },
    {
      id: 82,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/17.jpg",
      isCenter: false,
    },
    {
      id: 83,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/18.jpg",
      isCenter: false,
    },
    {
      id: 84,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/19.jpg",
      isCenter: false,
    },
    {
      id: 85,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/20.jpg",
      isCenter: false,
    },
    {
      id: 86,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/21.jpg",
      isCenter: false,
    },
    {
      id: 87,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/22.jpg",
      isCenter: false,
    },
    {
      id: 89,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/23.jpg",
      isCenter: false,
    },
    {
      id: 90,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/24.jpg",
      isCenter: false,
    },
    {
      id: 91,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/25.jpg",
      isCenter: false,
    },
    {
      id: 92,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/26.jpg",
      isCenter: false,
    },
    {
      id: 93,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/27.jpg",
      isCenter: false,
    },
    {
      id: 94,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/28.jpg",
      isCenter: false,
    },
    {
      id: 95,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/29.jpg",
      isCenter: false,
    },
    {
      id: 96,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/30.jpg",
      isCenter: false,
    },
    {
      id: 97,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/31.jpg",
      isCenter: false,
    },
    {
      id: 98,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/32.jpg",
      isCenter: false,
    },
    {
      id: 99,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/33.jpg",
      isCenter: false,
    },
    {
      id: 100,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/34.jpg",
      isCenter: false,
    },
    {
      id: 101,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/35.jpg",
      isCenter: false,
    },
    {
      id: 102,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/36.jpg",
      isCenter: false,
    },
    {
      id: 103,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/37.jpg",
      isCenter: false,
    },
    {
      id: 104,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/38.jpg",
      isCenter: false,
    },
    {
      id: 105,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Posts",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/posts/39.jpg",
      isCenter: false,
    },
    {
      id: 106,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Packaging",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/packaging/1.jpg",
      isCenter: false,
    },
    {
      id: 107,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Packaging",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/packaging/2.jpg",
      isCenter: false,
    },
    {
      id: 108,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Packaging",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/packaging/3.jpg",
      isCenter: false,
    },
    {
      id: 109,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Packaging",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/packaging/4.jpg",
      isCenter: false,
    },
    {
      id: 110,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Packaging",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/packaging/5.jpg",
      isCenter: false,
    },
    {
      id: 111,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/1.jpg",
      isCenter: false,
    },
    {
      id: 112,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/2.jpg",
      isCenter: false,
    },
    {
      id: 113,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/3.jpg",
      isCenter: false,
    },
    {
      id: 114,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/4.jpg",
      isCenter: false,
    },
    {
      id: 115,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/5.jpg",
      isCenter: false,
    },
    {
      id: 116,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/6.jpg",
      isCenter: false,
    },
    {
      id: 117,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/7.jpg",
      isCenter: false,
    },
    {
      id: 118,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/8.jpg",
      isCenter: false,
    },
    {
      id: 119,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/9.jpg",
      isCenter: false,
    },
    {
      id: 120,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/10.jpg",
      isCenter: false,
    },
    {
      id: 121,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/11.jpg",
      isCenter: false,
    },
    {
      id: 122,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "3D",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/3D/12.jpg",
      isCenter: false,
    },
    {
      id: 123,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Standees",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/standees/1.jpg",
      isCenter: false,
    },
    {
      id: 124,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Standees",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/standees/2.jpg",
      isCenter: false,
    },
    {
      id: 125,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Standees",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/standees/3.jpg",
      isCenter: false,
    },
    {
      id: 126,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Standees",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/standees/4.jpg",
      isCenter: false,
    },
    {
      id: 127,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Standees",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/standees/5.jpg",
      isCenter: false,
    },
    {
      id: 128,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/1.jpg",
      isCenter: false,
    },
    {
      id: 129,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/2.jpg",
      isCenter: false,
    },
    {
      id: 130,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/3.jpg",
      isCenter: false,
    },
    {
      id: 131,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/4.jpg",
      isCenter: false,
    },
    {
      id: 132,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/5.jpg",
      isCenter: false,
    },
    {
      id: 133,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/6.jpg",
      isCenter: false,
    },
    {
      id: 134,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/7.jpg",
      isCenter: false,
    },
    {
      id: 135,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/8.jpg",
      isCenter: false,
    },
    {
      id: 136,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/9.jpg",
      isCenter: false,
    },
    {
      id: 137,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/10.jpg",
      isCenter: false,
    },
    {
      id: 138,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/11.jpg",
      isCenter: false,
    },
    {
      id: 139,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Interior Designs",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/interior/12.jpg",
      isCenter: false,
    },
    {
      id: 140,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Stickers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/stickers/1.jpg",
      isCenter: false,
    },
    {
      id: 141,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Stickers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/stickers/2.jpg",
      isCenter: false,
    },
    {
      id: 142,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Stickers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/stickers/3.jpg",
      isCenter: false,
    },
    {
      id: 143,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Stickers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/stickers/4.jpg",
      isCenter: false,
    },
    {
      id: 144,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Stickers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/stickers/5.jpg",
      isCenter: false,
    },
    {
      id: 145,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Corporate",
      subcategory: "Stickers",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/corporate/stickers/6.jpg",
      isCenter: false,
    },
  ];

  const webSubcategories = [
    "Logo",
    "Banners",
    "Book Covers",
    "Thumbnails",
    "Business Cards",
    "Flyers",
    "Posts",
    "Packaging",
    "3D",
    "Standees",
    "Interior Designs",
    "Stickers",
  ];

  projects = interleaveBySubcategory(projects, webSubcategories);

  const handleProjectClick = (project) => {
    console.log("Project clicked:", project);
  };

  return (
    <Suspense>
      <ProjectsCarousel
        projects={projects}
        subcategories={webSubcategories}
        category="Corporate"
        visiblePerPage={3}
        onProjectClick={handleProjectClick}
        showDetails={false}
      />
    </Suspense>
  );
}
