"use client";

import React from "react";
import ProjectsCarousel from "@/components/projects/Projects";

export default function WebDevelopmentPage() {
  // ---- TODO: fill this array with your project objects ----
  // Example project object shape:
  // {
  //   id: 1,
  //   title: "Project Name",
  //   subtitle: "Short tag",
  //   category: "Web Development",
  //   subcategory: "WordPress", // or "Shopify" or "Custom"
  //   description: "Short description",
  //   bgGradient: "from-teal-900 via-black to-teal-900",
  //   textColor: "text-emerald-400",
  //   accentColor: "emerald-400",
  //   icon: null, // or an imported icon component
  //   svgPattern: "circuit",
  //   image: "/path/to/image.jpg",
  //   isCenter: false
  // }
  const projects = [
    {
      id: 1,
      title: "Antenna Now",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/1.jpg",
      isCenter: false,
    },
    {
      id: 2,
      title: "You & Min",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/2.jpg",
      isCenter: false,
    },
    {
      id: 3,
      title: "Rockford Mortage",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/3.jpg",
      isCenter: false,
    },
    {
      id: 4,
      title: "The Antenna",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/4.jpg",
      isCenter: false,
    },
    {
      id: 5,
      title: "Ali Jafri",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/5.jpg",
      isCenter: false,
    },
    {
      id: 6,
      title: "14 Star Limo",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/6.jpg",
      isCenter: false,
    },
    {
      id: 7,
      title: "Aussie Crops",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/7.jpg",
      isCenter: false,
    },
    {
      id: 8,
      title: "MTIS",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/8.jpg",
      isCenter: false,
    },
    {
      id: 9,
      title: "Genesyx",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/9.jpg",
      isCenter: false,
    },
    {
      id: 10,
      title: "Fashion",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/10.jpg",
      isCenter: false,
    },
    {
      id: 11,
      title: "Owl Watch Services",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/11.jpg",
      isCenter: false,
    },
    {
      id: 12,
      title: "My Income Guy",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/12.jpg",
      isCenter: false,
    },
    {
      id: 13,
      title: "Herbion",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/13.jpg",
      isCenter: false,
    },
    {
      id: 14,
      title: "GCI",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/14.jpg",
      isCenter: false,
    },
    {
      id: 15,
      title: "TSB",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/15.jpg",
      isCenter: false,
    },
    {
      id: 16,
      title: "ED LAB",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/16.jpg",
      isCenter: false,
    },
    {
      id: 17,
      title: "NGO LOOB",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/17.jpg",
      isCenter: false,
    },
    {
      id: 18,
      title: "Fin Talk",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "WordPress",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Wordpress/18.jpg",
      isCenter: false,
    },
    {
      id: 19,
      title: "IRC Booking System",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Custom",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Custom/1.jpg",
      isCenter: false,
    },
    {
      id: 20,
      title: "Smart Tender",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Custom",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Custom/2.jpg",
      isCenter: false,
    },
    {
      id: 21,
      title: "Cars Finder Pro",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Custom",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Custom/3.jpg",
      isCenter: false,
    },
    {
      id: 22,
      title: "Auto Cars",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Custom",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Custom/4.jpg",
      isCenter: false,
    },
    {
      id: 23,
      title: "Cars Finder Admin",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Custom",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Custom/5.jpg",
      isCenter: false,
    },
    {
      id: 24,
      title: "Clean Ui",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Custom",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Custom/6.jpg",
      isCenter: false,
    },
    {
      id: 25,
      title: "O 360",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Custom",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Custom/7.jpg",
      isCenter: false,
    },
    {
      id: 26,
      title: "Baseus",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Custom",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Custom/8.jpg",
      isCenter: false,
    },
    {
      id: 27,
      title: "Pop Charm",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Shopify",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Shopify/1.jpg",
      isCenter: false,
    },
    {
      id: 28,
      title: "Bechlo",
      subtitle: "Short tag",
      category: "Web Development",
      subcategory: "Shopify",
      description: "Short description",
      bgGradient: "from-teal-900 via-black to-teal-900",
      textColor: "text-emerald-400",
      accentColor: "emerald-400",
      icon: null,
      svgPattern: "circuit",
      image: "/assets/projects/web/Shopify/2.jpg",
      isCenter: false,
    },
  ];

  const webSubcategories = ["WordPress", "Shopify", "Custom"];

  const handleProjectClick = (project) => {
    // replace with navigation to project detail or modal open
    console.log("Project clicked:", project);
  };

  return (
          <ProjectsCarousel
            projects={projects}
            subcategories={webSubcategories}
            category="Web Development"
            visiblePerPage={3}
            onProjectClick={handleProjectClick}
          />

  );
}
